#!/usr/bin/env python3
"""
Simple Backend API Test for Referral Code System
"""

import requests
import json

BASE_URL = "https://afgmc.preview.emergentagent.com/api"

def test_referral_system():
    print("=== TESTING REFERRAL CODE SYSTEM ===\n")
    
    # Test 1: Login as talent
    print("1. Testing talent login...")
    login_data = {"email": "talent@test.com", "password": "test123"}
    response = requests.post(f"{BASE_URL}/auth/login", json=login_data)
    print(f"Status: {response.status_code}")
    
    if response.status_code == 200:
        data = response.json()
        talent_token = data.get("access_token")
        talent_id = data.get("user", {}).get("id")
        print(f"✅ Talent login successful - ID: {talent_id}")
    else:
        print(f"❌ Login failed: {response.text}")
        return
    
    # Test 2: Generate referral code
    print("\n2. Testing referral code generation...")
    headers = {"Authorization": f"Bearer {talent_token}"}
    response = requests.post(f"{BASE_URL}/talent/generate-code", headers=headers)
    print(f"Status: {response.status_code}")
    
    if response.status_code == 200:
        data = response.json()
        code = data.get("code")
        print(f"✅ Code generated: {code}")
        print(f"Generated by: {data.get('generated_by_name')}")
    else:
        print(f"❌ Code generation failed: {response.text}")
        return
    
    # Test 3: Test weekly limit
    print("\n3. Testing weekly limit...")
    response = requests.post(f"{BASE_URL}/talent/generate-code", headers=headers)
    print(f"Status: {response.status_code}")
    print(f"Response: {response.text}")
    
    if response.status_code == 400:
        data = response.json()
        if "week" in data.get("detail", "").lower():
            print("✅ Weekly limit working correctly")
        else:
            print(f"⚠️ Unexpected error: {data.get('detail')}")
    
    # Test 4: Get my codes
    print("\n4. Testing get my codes...")
    response = requests.get(f"{BASE_URL}/talent/my-codes", headers=headers)
    print(f"Status: {response.status_code}")
    
    if response.status_code == 200:
        codes = response.json()
        print(f"✅ Retrieved {len(codes)} codes")
        if codes and code in [c.get("code") for c in codes]:
            print("✅ Generated code found in list")
    else:
        print(f"❌ Failed: {response.text}")
    
    # Test 5: Code validation - same codes
    print("\n5. Testing code validation (same codes)...")
    validation_data = {"code1": code, "code2": code}
    response = requests.post(f"{BASE_URL}/auth/validate-codes", json=validation_data)
    print(f"Status: {response.status_code}")
    print(f"Response: {response.text}")
    
    if response.status_code == 400:
        data = response.json()
        if "different" in data.get("detail", "").lower():
            print("✅ Same code validation working correctly")
    
    # Test 6: Code validation - invalid codes
    print("\n6. Testing code validation (invalid codes)...")
    validation_data = {"code1": "9999", "code2": "8888"}
    response = requests.post(f"{BASE_URL}/auth/validate-codes", json=validation_data)
    print(f"Status: {response.status_code}")
    print(f"Response: {response.text}")
    
    if response.status_code == 400:
        data = response.json()
        if "invalid" in data.get("detail", "").lower():
            print("✅ Invalid code validation working correctly")
    
    # Test 7: Admin login
    print("\n7. Testing admin login...")
    admin_login = {"email": "admin@test.com", "password": "test123"}
    response = requests.post(f"{BASE_URL}/auth/login", json=admin_login)
    print(f"Status: {response.status_code}")
    
    if response.status_code == 200:
        data = response.json()
        admin_token = data.get("access_token")
        print("✅ Admin login successful")
    else:
        print(f"❌ Admin login failed: {response.text}")
        return
    
    # Test 8: Update talent rating
    print("\n8. Testing talent rating update...")
    admin_headers = {"Authorization": f"Bearer {admin_token}"}
    response = requests.put(f"{BASE_URL}/admin/talent/{talent_id}/rating?rating=5", headers=admin_headers)
    print(f"Status: {response.status_code}")
    print(f"Response: {response.text}")
    
    if response.status_code == 200:
        print("✅ Rating update successful")
    else:
        print("❌ Rating update failed")
    
    print("\n=== TESTING COMPLETE ===")

if __name__ == "__main__":
    test_referral_system()